import { Quicksand } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand(
  {
    subsets: ["latin"],
    weight: ['700'],
    display: 'swap'
  }
);

export const metadata = {
  title: "Ravikant Sharma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" >
      <body className={quicksand.className}>
        {children}</body>
    </html >
  );
}
